### ISSUE TITLE
設定画面の項目をセクション化する

### ISSUE THREAD

**Issue by kalupas226** [2017pro02/jinkawa-ios#20]

**Comment by HironariM** [comment]
` viewDidLoad() `内で` SettingTableView`の中身がnilになってdelegateをはじめとするUITableViewのメソッドでエラーがおきます。Outlet接続はしていてstoryboardのクラス設定もしています。ほかにどんな原因が考えられますか。お手上げです。助けてください。

`
import UIKit

class SettingViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
    
    @IBOutlet weak var SettingTableView: UITableView!
    
    let sectionTitle:[String] = ["設定", "お問合わせ"]
    let settingItem:[String] = ["通知のオン/オフ", "入力情報の確認"]
    let contactItem:[String] = ["陣川あさひ町会"]
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 11.0, *) {
        navigationController?.navigationBar.prefersLargeTitles = true
        }
        
        SettingTableView.delegate = self
        SettingTableView.dataSource = self
        
        SettingTableView.register(UITableViewCell.self, forCellReuseIdentifier: "SettingCell")
        
        //空のセルの境界線を消す
        SettingTableView.tableFooterView = UIView(frame: .zero)
        
        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        return sectionTitle.count
    }

    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return sectionTitle[section]
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        switch section {
            case 0:
                return settingItem.count
            case 1:
                return contactItem.count
            default:
                return 0
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "SettingCell", for: indexPath)
        switch indexPath.section {
        case 0:
            cell.textLabel?.text = settingItem[indexPath.row]
        case 1:
            cell.textLabel?.text = contactItem[indexPath.row]
        default:
            break
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        print("セクション番号：\(indexPath.section) セル番号：\(indexPath.row)")
    }
    
    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
`

**Comment by kalupas226** [comment]
バイト終わったから今から取り掛かるね

**Comment by kalupas226** [comment]
修正したプログラム上げたので、見てみて〜
